### ISSUE TITLE
Aborting with `malloc(): invalid size (unsorted)`

### ISSUE THREAD

**Issue by informathemusic** [fivdi/i2c-bus#100]
I am getting this error right after running my nodejs project:
```txt
malloc(): invalid size (unsorted)
Aborted
```

Any help is appreciated, thank you in advance!

**Comment by fivdi** [comment]
Please post a complete but short program that can be used to reproduce this problem.

**Comment by fivdi** [comment]
i2c-bus itself doesn't call malloc.

**Comment by informathemusic** [comment]
Resetting my RPI fixed it.
But for the code, I could've just used the lcdi2c library and it would have crashed
