### ISSUE TITLE
index.d.ts

### ISSUE THREAD

**Issue by PizzaProgram** [fivdi/i2c-bus#106]
Please include `index.d.ts` in the main directory because it helps a lot to understand definitions about this module.

_It took me 1 year to realize it exists! 
It would have spared me 10+ hours.
It would help others too, who are not using VScode from the beginning, like me._

... or at least mention it at the Readme.md file with a link to it.

Thanks :-)

**Comment by fivdi** [comment]
Which `index.d.ts` is being referred to? Is it the one [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/i2c-bus)?

**Comment by PizzaProgram** [comment]
YES.

**Comment by PizzaProgram** [comment]
Thanks :) Perfect!

**Comment by fivdi** [comment]
Section [TypeScript Type Definitions](https://github.com/fivdi/i2c-bus#typescript-type-definitions) was added to the README to document the availability of the TypeScript type definitions.

> Thanks :) Perfect!

You're welcome.
