### ISSUE TITLE
Can't it be used on orange pi 3 LTS?

### ISSUE THREAD

**Issue by VampireMao** [fivdi/i2c-bus#113]
![image](https://user-images.githubusercontent.com/26102623/199036836-d18f8ea6-e7a0-4240-bdbb-c0478f57dfb8.png)

Cause LCD1602 black screen

**Comment by fivdi** [comment]
I have never tried i2c-bus on an Orange Pi 3 as I don't have one. I see no reason why i2c-bus shouldn't work on an Orange Pi 3.

This issue you are seeing is highly unlikely to be an i2c-bus issue. You will need to read the appropriate datasheets in order to figure out how to drive the LCD.
