### ISSUE TITLE
Interrupt based callback?

### ISSUE THREAD

**Issue by crosofg** [fivdi/i2c-bus#16]
I am trying to use this for MCP23017. How do I set a interrupt based callback. I need to get the onchange callback .

**Comment by fivdi** [comment]
If I'm not mistaken, the interrupt-on-change interrupts can be detected on the INTA/INTB pins of the MCP23017. Is this correct? If so, these pins could be wired to GPIO pins configured as inputs on the Raspberry Pi / BeagleBone, or whatever the system happend to be. The [onoff](https://github.com/fivdi) package can then be used to detect these interrupts. onoff can be used for low latency interrupt detection (without polling.)

**Comment by fivdi** [comment]
Please let me know whether or not I've interpreted the requirement correctly here.

**Comment by crosofg** [comment]
Yes, you are correct. Interrupt are detected on INTA / B. I think onff package can work

**Comment by fivdi** [comment]
Ok, give it a try and let us know how it goes :)

**Comment by fivdi** [comment]
@crosofg was it possible to resolve the issue with onoff?

**Comment by crosofg** [comment]
@fivdi yes that worked. Thanks

**Comment by fivdi** [comment]
Excellent, thanks for the feedback.
