### ISSUE TITLE
I/O error crash

### ISSUE THREAD

**Issue by Proamp** [fivdi/i2c-bus#60]
An error cause node-red crash, when I disconnect SDA or SCL or power from working device. 
Tested with PI zero-w and OLED display on 1306 chip. I use node   node-red-contrib-oled.

20 Oct 17:26:53 - Error: EREMOTEIO: remote I/O error, write
at Object.fs.writeSync (fs.js:735:20)
at Bus.i2cWriteSync (/home/pi/.node-red/node_modules/i2c-bus/i2c-bus.js:348:13)
nodered.service: Main process exited, code=exited, status=1/FAILURE

**Comment by fivdi** [comment]
A remote i/o error is to be expected if the device is disconnected or powered down and an attempt is made to access the device. To avoid the crash it would be necessary for your application to handle the exception. This isn't something that can be handled by the i2c-bus module.

**Comment by Proamp** [comment]
Ok. I understand. Thank you.
