### ISSUE TITLE
What (if any) breaking changes 3 vs 4

### ISSUE THREAD

**Issue by dkebler** [fivdi/i2c-bus#63]
I am just getting back to a project that uses your package and see that you have bumped to 4.0. 

Before I upgrade can you point out any breaking changes I might face upgrading.  I saw no specific mention in the readme or in any of the releases.

Here is the code that will that would use the update
https://git.kebler.net/UCOMmandIt/uci-i2c-bus/src/branch/master/src/bus.js

as long as you did not change the api calls (name or arguments) I'm probably good to go.

**Comment by fivdi** [comment]
The breaking change in i2c-bus@4.0.0 was the removal of Windows support. This is mentioned in [History.md](https://github.com/fivdi/i2c-bus/blob/master/History.md#400--jul-25-2018) but it isn't flagged as a breaking change.

The API calls have not changed so if you were not relying on the Windows functionality you should be good to go.
