### ISSUE TITLE
Include Advice to verify 7 bits only in address

### ISSUE THREAD

**Issue by cesarjhony** [fivdi/i2c-bus#75]
Please include advice "Check 7 bits only in device address" on the REMOTE I/O ERROR.
Currently it show only:
```
Error: , Remote I/O error
....
```
Pointing to first line of my code like this:
`i2c1.writeByteSync(MCP23017_1_ADDR, IODIRA, 0b00000000);`

In my few experience with i2c I did forget the rule "just 7 bits for address, the last is for W/R", because of that detail I did spend a lot of time thinking if my chip was damaged.

**Comment by fivdi** [comment]
[writeByteSync](https://github.com/fivdi/i2c-bus/blob/v4.0.10/i2c-bus.js#L407-L415) invokes [checkAddress](https://github.com/fivdi/i2c-bus/blob/v4.0.10/i2c-bus.js#L59-L63) which is implemented as follows:
```js
const checkAddress = (addr) => {
  if (!Number.isInteger(addr) || addr < 0  || addr > 0x7f) {
    throw new Error('Invalid I2C address ' + addr);
  }
};
```
If the address  `addr` is outside the range 0 to 0x7f an "Invalid I2C address" error will be thrown, not a "Remote I/O error". Checking to see if `addr` is outside the range 0 to 0x7f is the same as checking to see if the address requires more than 7 bits.

Please provide a complete program that can be used to reproduce the error.

**Comment by fivdi** [comment]
The possible addresses for an MCP23017 are 0x20 through 0x27. Did you by any chance specify the address shifted 1 bit left, i.e., as 0x40 through 0x4e? If this is the case, 0x40 through 0x4e are still valid I2C addresses that fit in 7 bits. It's not possible to throw an error indicating that the address is incorrect.

**Comment by fivdi** [comment]
There isn't a TODO for i2c-bus here so I'll go ahead and close the issue.
