### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by fivdi** [fivdi/i2c-bus#81]
* [x] Mention that bytes are unsigned integers in the range 0 to 255
* [x] Mention that words are unsigned integers in the range 0 to 65535
* [x] Mention that buffers are instances of [Buffer](https://nodejs.org/dist/latest/docs/api/buffer.html#buffer_buffer)
~~* [ ] Mention that I2C addresses don't need to be left shifted 1 bit~~
* [x] Rename the [Methods](https://github.com/fivdi/i2c-bus#methods) section of the README to "Functions"
* [x] Fix [this comment](https://github.com/fivdi/i2c-bus/blob/master/example/i2cdetect-quick.js#L7-L8) as i2cscan.js is now called i2cdetect.js
* [x] Make a better Fritzing
* [x] Add an example that uses plain I2C and Buffers

**Comment by jscaglia** [comment]
> * Mention that buffers are instances of [Buffer](https://nodejs.org/dist/latest/docs/api/buffer.html#buffer_buffer)

Hi, a question.
If I want to save the word "test" on my NFC card.

I want to use the following methods (I don't know if it's okay to use these)

0x24 is my board address.
7 is the length I want to read

bus.i2cReadSync (0x24, 7, buffer?)
bus.i2cWrite (0x24, 7, buffer ?, cb?)

But I don't know what buffer is and cb ... will they have any example to pass me?

Greetings and thanks

**Comment by fivdi** [comment]
@jscaglia please open a new issue to discuss your problem,
