### ISSUE TITLE
am2322 of humidity & temperature sensor

### ISSUE THREAD

**Issue by raspberrypi-duke** [fivdi/i2c-bus#91]
Hello,
I use am2322 of humidity & temperature sensor and raspberry pi. Is there a way using wake-up and the wait(1000μs) by the async function? When wake-up is done by the read function, a small error goes out to a server console. 
```js
// create the register
const addr = 0x5C;
const cmd = 0x03;
const start = 0x00;
const length = 0x04;
const wbuf = Buffer.from([cmd, start, length]);
const rbuf = Buffer.alloc(8);
var sensor = [0, 0];

// wake-up the sensor
i2c.openPromisified(1).
then(i2c1 => i2c1.receiveByte(addr).
   then(_ => {
      return new Promise((resolve) => {
         setTimeout(() => {
            resolve(i2c1.close());
         }, 1);
      })
   })
).catch(console.log);

// read the sensor
i2c.openPromisified(1).
then(i2c1 => i2c1.i2cWrite(addr, wbuf.length, wbuf).
   then(_ => {
      return new Promise((resolve) => {
         setTimeout(() => {
            resolve(i2c1.i2cRead(addr, rbuf.length, rbuf));
         }, 1);
      })
   }).
   then(data => {
      sensor[1] = data.buffer.readUInt16BE(2) / 10.0; // humidity
      sensor[0] = data.buffer.readUInt16BE(4) / 10.0; // temperature
   }).
   then(_ => i2c1.close())
).catch(console.log);
```

Thanks,
duke :)

**Comment by fivdi** [comment]
I'm not familiar with the am2322 so I may not be able to provide much help.

What error message is displayed on the console by the program posted above?

**Comment by raspberrypi-duke** [comment]
Hi,

Thank you very much for your reply.

am2322 datasheet
https://www.isweek.com/Uploads/20180528/5b0bbbc09cff2.pdf

error display
{ [Error: , Remote I/O error] errno: 121, code: ‘’, syscall: ‘receiveByte’ }

thanks,
duke :)

**Comment by fivdi** [comment]
> Device address is 0xb8.
> I used for a raspberry pi, so it shifts 1 bit(device address is 0x5c).

Yes, this is the correct thing to do.

The am2322 appears to have very specific and unusual timing requirements. 

There is a sample Python program on the following page that reads from an am2322:

https://www.denshi.club/pc/raspi/5raspberry-pi-zeroiot26-4-am2322.html

The Python program call `read_byte` (which is the same as `receiveByte` in JavaScript) and expects an error. When the error occurs, it then read the temperature and humidity.

You could try to convert the Python program to JavaScript to see if it works.

**Comment by raspberrypi-duke** [comment]
Hi, fivdi.

Thank you very much for your best software.

Is there a way to close the i2c which opened in Wake-up? When not closing i2c and reading a sensor many times, will it be lack of a memory?

thanks,
duke :)

**Comment by fivdi** [comment]
I see that the code in the first comment has completely changed. Please don't change code like this. It will make it difficult or impossible for people reading the issue later to understand everything. Post the modified code in a new comment instead.

Does the code now function correctly?

The code should be re-structured to use only one `PromisifiedBus` object , not two. Then it will not be necessary to close the first one. The code should also be modified to prevent the "wake-up" and "read the sensor" code from running at the same time which is currently the case.

**Comment by raspberrypi-duke** [comment]
Hi, fivdi.

Cord change, I’m sorry. An error goes out to this cord in wake, a sensor can be read. I wanted to know whether it'll be lack of a memory by not closing i2c of wake.

thanks,
duke :)

**Comment by fivdi** [comment]
Yes, not closing the bus object will cause file descriptor leaks.

You should use catch to ignore the error.

**Comment by raspberrypi-duke** [comment]
Hi, fivdi.

It can't close by this cord.
Could you instruct the best way?

// wake-up the sensor
i2c.openPromisified(1).
then(i2c1 => i2c1.receiveByte(addr).
   then(_ => {
      return new Promise((resolve) => {
         setTimeout(() => {
            resolve(i2c1.close());
         }, 1);
      })
   })
).
catch(i2c1 => {
   i2c1.close();
   console.log;
});

thanks,
duke :)

**Comment by fivdi** [comment]
Please take a look at a Promises tutorial.
