### ISSUE TITLE
Please update your code to address deprecated Buffer() call use

### ISSUE THREAD

**Issue by dachshund-digital** [fivdi/i2c-bus#94]
Please update your code to address deprecated Buffer() call use.  Following warning now results when using your module.

(node:14197) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by fivdi** [comment]
There are no deprecated usages of `Buffer()` in the current i2c-bus codebase or at least I can't find any.
What version of i2c-bus are you using? Perhaps there were deprecated usages of `Buffer()` in older versions of i2c-bus.
Can you provide code that can be used to reproduce the issue?

**Comment by fivdi** [comment]
As mentioned above there are no deprecated usages of `Buffer()` in the current i2c-bus codebase so I'll go ahead and close the issue.
